# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

# Install the required python libraries
steps:
- script: pip install -r requirements.txt
  displayName: 'Install requirements'


# Run the Robot framework Tests
- script: robot --rpa -d results -x execution-report.xml Test/virtuoso.robot
  displayName: 'Run Virtuoso Test'
  continueOnError: true
  env:
    VIRTUOSO_TOKEN: $(VIRTUOSO_TOKEN)
    

# Optional Step to add run to Test Run (NOTE: It does not link the executions)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'results'
    ArtifactName: 'results'
    publishLocation: 'Container'

#Optional Task to publish JUNIT results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/results/execution-report.xml'
